/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoopBackApplication);
  }
}(this, function(expect, LoopBackApplication) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoopBackApplication.FullstrideGameControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FullstrideGameControllerApi', function() {
    describe('fullstrideGameControllerCount', function() {
      it('should call fullstrideGameControllerCount successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerCount
        //instance.fullstrideGameControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fullstrideGameControllerCreate', function() {
      it('should call fullstrideGameControllerCreate successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerCreate
        //instance.fullstrideGameControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fullstrideGameControllerDeleteById', function() {
      it('should call fullstrideGameControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerDeleteById
        //instance.fullstrideGameControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fullstrideGameControllerFind', function() {
      it('should call fullstrideGameControllerFind successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerFind
        //instance.fullstrideGameControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fullstrideGameControllerFindById', function() {
      it('should call fullstrideGameControllerFindById successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerFindById
        //instance.fullstrideGameControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fullstrideGameControllerReplaceById', function() {
      it('should call fullstrideGameControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerReplaceById
        //instance.fullstrideGameControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fullstrideGameControllerUpdateAll', function() {
      it('should call fullstrideGameControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerUpdateAll
        //instance.fullstrideGameControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fullstrideGameControllerUpdateById', function() {
      it('should call fullstrideGameControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test fullstrideGameControllerUpdateById
        //instance.fullstrideGameControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
